[package]
name = "veritas-identity-registry"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "veritas_identity_registry"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
veritas-contract-shared = { path = "../shared" }
