[package]
name = "veritas-asset-engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "veritas_asset_engine"
path = "src/lib.rs"

[dependencies]
veritas-contract-shared = { path = "../shared" }
veritas-identity-registry = { path = "../identity-registry" }
veritas-compliance-engine = { path = "../compliance-engine" }
